version: '3.8'

services:
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${TYPEORM_PASSWORD}'
            MYSQL_DATABASE: '${TYPEORM_DATABASE}'
            MYSQL_USER: '${TYPEORM_USERNAME}'
            MYSQL_PASSWORD: '${TYPEORM_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'nestjsmysql:/var/lib/mysql'
        networks:
            - nesjs-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        restart: unless-stopped

    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped


networks:
    nesjs-network:
volumes:
    nestjsmysql:
        driver: local
